brazillian_ecom:
  outputs:
    dev:
      dbname: brazil_ecom
      host: "{{ env_var('POSTGRES_HOST') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
  target: dev
