version: 2

sources:
  - name: brazil_ecom
    schema: public
    database: brazil_ecom
    tables:
      - name: olist_order_items_dataset
      - name: olist_order_payments_dataset
      - name: olist_orders_dataset
      - name: olist_products_dataset
